FROM php:8.4-cli

RUN apt-get update && apt-get install -y \
    libpcre2-dev \
    libssl-dev \
    zlib1g-dev \
    libcurl4-openssl-dev \
    libc-ares-dev \
    autoconf \
    build-essential \
    git \
    unzip \
    && rm -rf /var/lib/apt/lists/*

RUN pecl install -D 'enable-openssl="yes" enable-swoole-curl="yes"' swoole \
    && docker-php-ext-enable swoole

WORKDIR /app